name: 'Test and lint'

description: 'Run tests and code linters'

runs:
  using: "composite"
  steps:
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Run linter
      working-directory: frontend
      run: npm run lint

    - name: Start test DB
      run: docker-compose -f .github/actions/docker-compose.test.yml up -d db

    - name: Run backend tests
      run: docker-compose -f .github/actions/docker-compose.test.yml up backend

    - name: Clean up
      run: docker-compose -f .github/actions/docker-compose.test.yml down -v
