name: Docker build and push

on:
  workflow_call:
    inputs:
      tag:
        description: Tag to push the Docker image to
        type: string
        required: true
    secrets:
      dockerhub_token:
        required: true

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: georgevm185
          password: ${{ secrets.dockerhub_token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: georgevm185/slack-archive:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
