name: Release

on:
  push:
    branches:
      - master

jobs:
  lint-frontend:
    name: Run frontend code linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run linter
        working-directory: frontend
        run: npm run lint

  test-backend:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Start test DB
        run: docker-compose -f .github/docker-compose.test.yml up -d db

      - name: Build backend image
        run: docker-compose -f .github/docker-compose.test.yml build backend

      - name: Run backend tests
        run: docker-compose -f .github/docker-compose.test.yml up backend

      - name: Clean up
        run: docker-compose -f .github/docker-compose.test.yml down -v

  release-frontend:
    name: Deploy frontend with Netlify
    runs-on: ubuntu-latest
    needs: [lint-frontend, test-backend]
    steps:
      - name: Trigger Netlify Build Hook
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK

  release-backend:
    name: Push Backend Docker image
    runs-on: ubuntu-latest
    needs: [lint-frontend, test-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest
          file: dockerfiles/backend.Dockerfile
