name: Test

on:
  workflow_call:

jobs:
  test-server:
    name: Test server
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull job image
        env:
          tag: job-${{ github.run_id }}
        run: |
          docker pull georgevm185/slack-archive:$tag
          docker tag georgevm185/slack-archive:$tag slack-archive_test:latest

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml -p slack-archive run --rm test

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn run:web lint
